@extends('layouts.guest')

@section('title', 'Privacy Policy')

@section('content')

<div class="auth-layout">
    <div class="auth-container">

 
    <a href="{{ route('login') }}" class="auth-logo">
        <img src="{{ asset('assets/img/logo.webp') }}" alt="SmartHealthIoT">
        <span>SmartHealthIoT</span>
    </a>

    <div class="auth-card">

        <div class="auth-card-header">
            <div class="auth-icon">
                <i class="bi bi-shield-lock"></i>
            </div>

            <h1 class="auth-title">Privacy Policy</h1>

            <p class="auth-subtitle">
                How SmartHealthIoT handles information.
            </p>
        </div>

        <div class="auth-form">

            <div class="form-group">
                <h5>1. Information We Collect</h5>

                <p class="text-muted">
                    SmartHealthIoT may collect information required to provide
                    and operate the platform, including account information,
                    patient information, device information, and health
                    readings generated by connected devices.
                </p>
            </div>

            <div class="form-group">
                <h5>2. How We Use Information</h5>

                <p class="text-muted">
                    Information may be used to authenticate users, manage
                    patients and devices, display health monitoring data,
                    provide notifications, maintain the platform, and improve
                    system reliability.
                </p>
            </div>

            <div class="form-group">
                <h5>3. Health Information</h5>

                <p class="text-muted">
                    Health-related information should be treated as sensitive
                    information. Access should be limited to authorized users
                    according to the permissions configured within the system.
                </p>
            </div>

            <div class="form-group">
                <h5>4. Device Information</h5>

                <p class="text-muted">
                    Connected IoT devices may transmit information such as
                    device identifiers, sensor readings, battery information,
                    and timestamps.
                </p>
            </div>

            <div class="form-group">
                <h5>5. Data Security</h5>

                <p class="text-muted">
                    We use reasonable technical and organizational measures
                    intended to protect information against unauthorized
                    access, alteration, disclosure, or destruction.
                </p>
            </div>

            <div class="form-group">
                <h5>6. Data Retention</h5>

                <p class="text-muted">
                    Information may be retained for as long as necessary to
                    operate the platform, meet legitimate operational
                    requirements, or comply with applicable obligations.
                </p>
            </div>

            <div class="form-group">
                <h5>7. Your Rights</h5>

                <p class="text-muted">
                    Depending on applicable law and your relationship with
                    the organization operating SmartHealthIoT, you may have
                    rights regarding access, correction, deletion, or other
                    handling of your personal information.
                </p>
            </div>

            <div class="form-group">
                <h5>8. Contact Us</h5>

                <p class="text-muted">
                    If you have questions about this Privacy Policy or how
                    information is handled, please contact the SmartHealthIoT
                    administrator.
                </p>
            </div>

            <div class="alert alert-warning">
                <i class="bi bi-exclamation-triangle me-2"></i>
                This is a project-specific privacy policy template. It should
                be reviewed and adapted to your actual data practices and
                applicable privacy laws before production use.
            </div>

        </div>

        <p class="auth-footer-text">
            <a href="{{ route('login') }}" class="auth-link">
                <i class="bi bi-arrow-left"></i>
                Back to login
            </a>
        </p>

    </div>

   @include('layouts.guestfooter')

</div>
 

</div>

@endsection
